### ISSUE TITLE
DOM module/required error

### ISSUE THREAD

**Issue by Triplemanus** [hndfaw/activity-tracker-starter#11]
@hndfaw 
P1
Need to get DOM to accept our class module exports in javascript

`if (typeof module !== "undefined" /*&& typeof module.exports !== "undefined"*/) {
  module.exports = Hydration;
 }`

**Comment by hndfaw** [comment]
Thanks @Triplemanus, will work on this issue today together!

**Comment by hndfaw** [comment]
Done.
